#!/bin/sh
# clean up all files that are easily regenerated by the make.sh script

name=tutorial
files="*~ demo log.log *.dst.txt *.html $name.txt $name.tex $name.p.tex ${name}_rst.* $name.rst $name.sphinx.rst $name.odt $name.st $name.epytext $name.wiki __tmp.do.txt ._tmp.do.txt *.ps *.pdf *.*tex log.log *.*xml *.aux *.log *.dvi *.out sphinx-rootdir"
dir=`pwd`
echo "Removing in $dir:"
/bin/ls $files 2> /dev/null
rm -rf $files
