#!/bin/sh

# ------------------- scientific_writing talk ---------------------
name=scientific_writing

# Note: since Doconce syntax is demonstrated inside !bc/!ec
# blocks we need a few fixes

doconce format html $name --pygments-html-style=perldoc --html-style=solarized
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
mv -f $name.html ${name}_solarized.html
doconce format html $name --pygments-html-style=default
mv -f $name.html ${name}_plain.html

doconce format html $name --pygments-html-style=perldoc
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
cp $name.html ${name}_deck.html
doconce slides_html ${name}_deck deck --html-slide-theme=sandstone.default
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
# Fix selected backslashes inside verbatim envirs that doconce has added
# (only a problem at the places where we want to show full doconce code with
# labels in !bc-!ec envirs - other labels in math blocks need backslash...).
doconce replace '\label{this:section}' 'label{this:section}' ${name}_deck.html
doconce replace '\label{fig1}' 'label{fig1}' ${name}_deck.html
doconce replace '\label{demo' 'label{demo' ${name}_deck.html

doconce format html $name --pygments-html-style=native
doconce slides_html $name reveal --html-slide-theme=darkgray
# Fix selected backslashes inside verbatim envirs that doconce has added
# (only a problem when we want to show full doconce code with
# labels in !bc-!ec envirs).
doconce replace '\label{this:section}' 'label{this:section}' $name.html
doconce replace '\label{fig1}' 'label{fig1}' $name.html
doconce replace '\label{demo' 'label{demo' $name.html


doconce format pdflatex $name --minted-latex-style=trac
doconce ptex2tex $name envir=minted -DBOOK
pdflatex -shell-escape $name
mv -f $name.pdf ${name}_minted.pdf

doconce format pdflatex $name
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
doconce ptex2tex $name envir=ans:nt -DBOOK
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
pdflatex $name
mv -f $name.pdf ${name}_anslistings.pdf

# sphinx doesn't handle math inside code well, we drop it since
# other formats demonstrate doconce writing this way
doconce format sphinx $name
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
doconce sphinx_dir author="H. P. Langtangen" theme=pyramid $name
python automake_sphinx.py

doconce format pandoc $name  # Markdown (pandoc extended)
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
doconce format gwiki  $name  # Googlecode wiki
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi

# These don't like slides with code after heading:
#doconce format rst    $name  # reStructuredText
#doconce format plain  $name  # plain, untagged text for email

pygmentize -l text -f html -o ${name}_doconce.html ${name}.do.txt

cp -r ${name}*.pdf *.md *.gwiki ${name}*.html deck.js reveal.js fig ../demos/slides/

doconce format html sw_index.do.txt
cp sw_index.html ../demos/slides/index.html

# ------------------- short demo talk ---------------------

doconce format html demo # test
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi

# Make all the styles for the short demo talk
doconce slides_html demo all  # generates tmp_slides_html_all.sh
pygmentize -l text -f html -o demo_doconce.html demo.do.txt
sh -x tmp_slides_html_all.sh

doconce format pdflatex demo
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
doconce ptex2tex demo -DPALATINO envir=minted
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
pdflatex -shell-escape demo

cp -r demo.pdf demo_*.html reveal.js deck.js csss fig ../demos/slides/demo/
cat > ../demos/slides/demo/index.html <<EOF
<h1>Autogenerated slide styles</h1>
<b>Note:</b> View these slides in Firefox (not Chrome). Bring slide shows
up in separate tabs. You may need to reload some pages to get the
mathematics correctly rendered.
<ul>
<p><li> reveal.js: (the css style files are slightly changed: left-adjusted,
lower case headings with smaller fonts; "darkgray" corresponds to
the original "default" theme)
<ul>
<p><li><a href="demo_reveal_beige.html">reveal, beige theme</a>
<pre>
doconce format html demo --pygments-html-style=perldoc
doconce slides_html demo reveal --html-slide-theme=beige
</pre>
<li><a href="demo_reveal_beigesmall.html">reveal, beigesmall theme</a>
<pre>
doconce format html demo --pygments-html-style=perldoc
doconce slides_html demo reveal --html-slide-theme=beigesmall
</pre>
<li><a href="demo_reveal_darkgrey.html">reveal, darkgrey theme</a>
<pre>
doconce format html demo --pygments-html-style=native
doconce slides_html demo reveal --html-slide-theme=darkgray
</pre>
<li><a href="demo_reveal_serif.html">reveal, serif theme</a>
<pre>
doconce format html demo --pygments-html-style=perldoc
doconce slides_html demo reveal --html-slide-theme=serif
</pre>
<li><a href="demo_reveal_night.html">reveal, night theme</a>
<pre>
doconce format html demo --pygments-html-style=fruity
doconce slides_html demo reveal --html-slide-theme=night
</pre>
<li><a href="demo_reveal_simple.html">reveal, simple theme</a>
<pre>
doconce format html demo --pygments-html-style=autumn
doconce slides_html demo reveal --html-slide-theme=simple
</pre>
<li><a href="demo_reveal_sky.html">reveal, sky theme</a>
</ul>
<p><li> deck.js: (the css styles are slightly changed, mainly somewhat
smaller fonts for verbatim code)
<ul>
<p><li><a href="demo_deck_beamer.html">deck, beamer theme</a>
<pre>
doconce format html demo --pygments-html-style=autumn
doconce slides_html demo deck --html-slide-theme=beamer
</pre>
<li><a href="demo_deck_mnml.html">deck, mnml theme</a>
<pre>
doconce format html demo --pygments-html-style=default
doconce slides_html demo deck --html-slide-theme=mnml
</pre>
<li><a href="demo_deck_neon.html">deck, neon theme</a>
<pre>
doconce format html demo --pygments-html-style=fruity
doconce slides_html demo deck --html-slide-theme=neon
</pre>
<li><a href="demo_deck_sandstone_aurora.html">deck, sandstone.aurora theme</a>
<pre>
doconce format html demo --pygments-html-style=fruity
doconce slides_html demo deck --html-slide-theme=sandstone.aurora
</pre>
<li><a href="demo_deck_sandstone_dark.html">deck, sandstone.dark theme</a>
<pre>
doconce format html demo --pygments-html-style=native
doconce slides_html demo deck --html-slide-theme=sandstone.dark
</pre>
<li><a href="demo_deck_sandstone_default.html">deck, sandstone.default theme</a>
<pre>
doconce format html demo --pygments-html-style=perldoc
doconce slides_html demo deck --html-slide-theme=sandstone.default
</pre>
<li><a href="demo_deck_sandstone_firefox.html">deck, sandstone.firefox theme</a>
<pre>
doconce format html demo --pygments-html-style=default
doconce slides_html demo deck --html-slide-theme=sandstone.firefox
</pre>
<li><a href="demo_deck_sandstone_light.html">deck, sandstone.light theme</a>
<li><a href="demo_deck_sandstone_mdn.html">deck, sandstone.mdn theme</a>
<pre>
doconce format html demo --pygments-html-style=emacs
doconce slides_html demo deck --html-slide-theme=sandstone.light
</pre>
<li><a href="demo_deck_sandstone_mightly.html">deck, sandstone.mightly theme</a>
<pre>
doconce format html demo --pygments-html-style=fruity
doconce slides_html demo deck --html-slide-theme=sandstone.mightly
</pre>
<li><a href="demo_deck_swiss.html">deck, swiss theme</a>
<pre>
doconce format html demo --pygments-html-style=autumn
doconce slides_html demo deck --html-slide-theme=swiss
</pre>
<li><a href="demo_deck_web-2_0.html">deck, web-2_0 theme</a>
<pre>
doconce format html demo --pygments-html-style=autumn
doconce slides_html demo deck --html-slide-theme=web-2.0
</pre>
</ul>
<li><a href="demo_dzslides_dzslides_default.html">dzslides</a>
<pre>
doconce format html demo --pygments-html-style=autumn
doconce slides_html demo dzslides --html-slide-theme=dzslides_default
</pre>
<li><a href="demo_csss_csss_default.html">csss</a> (black background instead
of the original rainbow background)
<pre>
doconce format html demo --pygments-html-style=monokai
doconce slides_html demo csss --html-slide-theme=csss_default
</pre>
<li><a href="demo.pdf">Handouts in PDF</a> (generated via LaTeX)
<li><a href="demo_doconce.html">Doconce source code for the slides</a>
<li>Doconce: Why and How, <a href="../scientific_writing.html">reveal w/darkgrey</a>, <a href="../scientific_writing_deck.html">deck w/sandstone.default</a>
</ul>
EOF