#!/bin/sh
# clean up all files that are easily regenerated by the make.sh script

name=manual
files="*~ demo log.log ${name}*.dst.txt ${name}*.html $name.txt ${name}*.tex ${name}_rst.* $name.rst $name.sphinx.rst $name.odt $name.st $name.epytext $name.gwiki __tmp.do.txt ._tmp.do.txt ${name}*.ps ${name}*.pdf _*.log *.*xml *.aux ${name}*.log ${name}*.dvi *.out sphinx-rootdir tmp.* ../../lib/doconce/doconce.py"
dir=`pwd`
echo "Removing in $dir:"
/bin/ls $files 2> /dev/null
rm -rf $files
rm -rf ../../build
rm -f ../../test/test.v


