#!/bin/sh
# clean up all files that are easily regenerated by the make.sh script

name=doconce
files="*~ _*.log *.dst.txt $name.html $name.txt $name.tex $name.p.tex ${name}_rst.* $name.rst $name.st $name.epytext $name.wiki __tmp.do.txt ._tmp.do.txt *.ps *.pdf *.*tex log.log *.*xml *.aux *.log *.dvi *.out sphinx-rootdir ../../lib/doconce/*.pyc ../../lib/doconce/doconce.py"
dir=`pwd`
echo "Removing in $dir:"
/bin/ls $files 2> /dev/null
rm -rf $files
rm -rf ../../build
rm -f ../../test/test.v


